### ISSUE TITLE
throws Cannot read property 'length' of undefined when running coverage reporting

### ISSUE THREAD

**Issue by bloody-ux** [rosswarren/babel-plugin-rewire-ts#13]
Cannot read property 'length' of undefined
    at PluginPass.CallExpression (/Users/bhtbed/workspace/project/test-project/node_modules/_@babel_plugin-proposal-decorators@7.10.5@@babel/plugin-proposal-decorators/lib/transformer-legacy.js:171:29)
    at newFn (/Users/bhtbed/workspace/openhome/isv-shop-mgnt/node_modules/_@babel_traverse@7.11.5@@babel/traverse/lib/visitors.js:175:21)
    at NodePath._call (/Users/bhtbed/workspace/openhome/isv-shop-mgnt/node_modules/_@babel_traverse@7.11.5@@babel/traverse/lib/path/context.js:55:20)
    at NodePath.call (/Users/bhtbed/workspace/openhome/isv-shop-mgnt/node_modules/_@babel_traverse@7.11.5@@babel/traverse/lib/path/context.js:42:17)
    at NodePath.visit (/Users/bhtbed/workspace/openhome/isv-shop-mgnt/node_modules/_@babel_traverse@7.11.5@@babel/traverse/lib/path/context.js:92:31)
    at TraversalContext.visitQueue (/Users/bhtbed/workspace/openhome/isv-shop-mgnt/node_modules/_@babel_traverse@7.11.5@@babel/traverse/lib/context.js:112:16)
    at TraversalContext.visitSingle (/Users/bhtbed/workspace/openhome/isv-shop-mgnt/node_modules/_@babel_traverse@7.11.5@@babel/traverse/lib/context.js:84:19)
    at TraversalContext.visit (/Users/bhtbed/workspace/openhome/isv-shop-mgnt/node_modules/_@babel_traverse@7.11.5@@babel/traverse/lib/context.js:140:19)
    at Function.traverse.node (/Users/bhtbed/workspace/openhome/isv-shop-mgnt/node_modules/_@babel_traverse@7.11.5@@babel/traverse/lib/index.js:82:17)
    at NodePath.visit (/Users/bhtbed/workspace/openhome/isv-shop-mgnt/node_modules/_@babel_traverse@7.11.5@@babel/traverse/lib/path/context.js:99:18)
Failed to collect coverage from /Users/bhtbed/workspace/project/test-project/src/pages/components/Address/index.jsx

**Comment by priyank-p** [comment]
Can you please provide more details? For example:
- What coverage tool are you using?
- It would be great if you could provide code that could reproduce this issue.

I am pretty sure it's the coverage tool or the way you are using it is the problem and not `babel-plugin-rewire-ts`.

**Comment by bloody-ux** [comment]
You're right, it looks like conflicting with `babel-plugin-lodash`, when this plugin is removed, it works.
